services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.3.1
    container_name: ${PROXY_CONTAINER:-codai_nginx_proxy}
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-data:/etc/nginx/conf.d
    networks:
      - codai_net

volumes:
  proxy-data:

networks:
  codai_net:
    driver: bridge
    name: ${CODAI_NETWORK:-nginx-proxy_net}
